version: '2'

services:
 postgres:
  image: postgres:latest
  volumes:
   - /srv/postgresql/data:/var/lib/postgresql/data
   - /srv/postgresql/backup:/backups
  environment:
   - POSTGRES_PASSWORD=123456
   - POSTGRES_USER=teamcity
   - POSTGRES_DB=teamcity
  ports:
   - "5432:5432"
                                                                                
 teamcity:
  image: jetbrains/teamcity-server:latest
  restart: unless-stopped
  volumes:
    - /srv/teamcity/data:/data/teamcity_server/datadir
    - /srv/teamcity/logs:/opt/teamcity/logs
  ports:
   - "8111:8111"

 teamcity_agent1:
  image: quintsys/teamcity-agent-ruby:latest
  restart: unless-stopped
  links:
   - teamcity:teamcity
  environment:
   - SERVER_URL=teamcity:8111
   - AGENT_NAME="tcagent_docker_001"

 teamcity_agent2:
  image: quintsys/teamcity-agent-ruby:latest
  restart: unless-stopped
  links:
   - teamcity:teamcity
  environment:
   - SERVER_URL=teamcity:8111
   - AGENT_NAME="tcagent_docker_002"

 teamcity_agent3:
  image: quintsys/teamcity-agent-ruby:latest
  restart: unless-stopped
  links:
   - teamcity:teamcity
  environment:
   - SERVER_URL=teamcity:8111
   - AGENT_NAME="tcagent_docker_003"