version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}
  teamcity_server_data: {}
  teamcity_server_logs: {}

services:

  postgres:
    build: ./postgres
    volumes:
      - /srv/postgresql/data:/var/lib/postgresql/data
      - /srv/postgresql/backups:/backups
    env_file: .env
    restart: always

  teamcity-server:
    build: jetbrains/teamcity-server:latest
    volumes:
      - /srv/teamcity/data:/data/teamcity_server/datadir
      - /srv/teamcity/logs:/opt/teamcity/logs
    ports:
      - 8111:8111
    depends_on:
      - postgres
    env_file: .env
    restart: always

  teamcity-agent:
    image: jetbrains/teamcity-minimal-agent:latest
    env_file: .env
    restart: always