version: '3'

services:

  postgres:
    build: ./postgres
    volumes:
      - /srv/postgresql/data:/var/lib/postgresql/data
      - /srv/postgresql/backups:/backups
    env_file: .env
    restart: always

  teamcity-server:
    image: jetbrains/teamcity-server:latest
    volumes:
      - /srv/teamcity/data:/data/teamcity_server/datadir
      - /srv/teamcity/logs:/opt/teamcity/logs
    ports:
      - 8111:8111
    depends_on:
      - postgres
    env_file: .env
    restart: always

  teamcity-agent:
    build: ./agents/ruby-nodejs
    env_file: .env
    restart: always
    scale: 3