version: '2'
services:
  postgres:
    build: ./postgres
    restart: always
    volumes:
      - '/srv/postgresql/data:/var/lib/postgresql/data'
      - '/srv/postgresql/backup:/backups'
    env_file: .env
    ports:
      - '5432:5432'
  teamcity:
    build: ./server
    restart: always
    volumes:
      - '/srv/teamcity/data:/data/teamcity_server/datadir'
      - '/srv/teamcity/logs:/opt/teamcity/logs'
    ports:
      - '8111:8111'
    depends_on:
      - postgres
  teamcity_agent:
    image: 'quintsys/teamcity-agent-ruby:latest'
    restart: always
    links:
      - 'teamcity:teamcity'
    environment:
      - 'SERVER_URL=teamcity:8111'